name: Wheels

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - requirements.txt
      - requirements_build.txt

jobs:
  build:
    name: Build ${{ matrix.arch }}-python${{ matrix.python }}-alpine${{ matrix.alpine }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9"]
        alpine: ["3.11", "3.12", "3.13"]
        arch: ["aarch64", "armhf", "armv7", "amd64", "i386"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: Prepare requirements
        run: cat requirements.txt requirements_build.txt > requirements_all.txt

      - name: Build wheels
        uses: ./
        with:
          tag: ${{ matrix.python }}-alpine${{ matrix.alpine }}
          arch: ${{ matrix.arch }}
          wheels-host: ${{ secrets.WHEELS_HOST }}      
          wheels-port: ${{ secrets.WHEELS_PORT }}
          wheels-user: ${{ secrets.WHEELS_USER }}
          wheels-key: ${{ secrets.WHEELS_KEY }}
          wheels-index: "https://claret.io/sandbox/drypatrick/wheels"
          upload: "lftp"
          ftp-host: ${{ secrets.FTP_HOST }}
          ftp-user: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PSW }}
          ftp-remote: "www/sandbox/drypatrick/wheels/"
          ftp-mirror-options: "--reverse --no-perms --only-missing" # --verbose
          apk: "build-base;libffi-dev;openssl-dev"
          requirements: "requirements_all.txt"
